services:
  pulsar-server:
    hostname: pulsar-server
    entrypoint: "bin/pulsar standalone"
    image: apachepulsar/pulsar:2.6.0
    ports:
      - 46650:6650
      - 48080:8080
  pulsar-producer:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - pulsar-server
    entrypoint: /root/pulsar_producer.py
  pulsar-consumer:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - pulsar-server
    entrypoint: /root/pulsar_consumer.py
